SELECT - '42.01'::zdecimal;
SELECT - '0'::zdecimal;
SELECT - 'nan'::zdecimal;
SELECT '55'::zdecimal;
SELECT '-55'::zdecimal;
SELECT ''::zdecimal;
SELECT 'x'::zdecimal;
SELECT '55 x'::zdecimal;
SELECT '127'::zdecimal;
SELECT '200'::zdecimal;
SELECT '-128'::zdecimal;
SELECT '-200'::zdecimal;

CREATE TABLE test_zdecimal (a zdecimal);
INSERT INTO test_zdecimal VALUES (-2), (-1), (0), (1), (2);
SELECT a FROM test_zdecimal;
SELECT a FROM test_zdecimal ORDER BY a;
DROP TABLE test_zdecimal;

SELECT '2'::zdecimal < 5;
SELECT 2 < '5'::zdecimal;
SELECT '5'::zdecimal < 2;
SELECT 5 < '2'::zdecimal;
SELECT '2'::zdecimal <= 5;
SELECT 2 <= '5'::zdecimal;
SELECT '5'::zdecimal <= 2;
SELECT 5 <= '2'::zdecimal;
SELECT '2'::zdecimal = 5;
SELECT 2 = '5'::zdecimal;
SELECT '5'::zdecimal = 2;
SELECT 5 = '2'::zdecimal;
SELECT '2'::zdecimal <> 5;
SELECT 2 <> '5'::zdecimal;
SELECT '5'::zdecimal <> 2;
SELECT 5 <> '2'::zdecimal;
SELECT '2'::zdecimal >= 5;
SELECT 2 >= '5'::zdecimal;
SELECT '5'::zdecimal >= 2;
SELECT 5 >= '2'::zdecimal;
SELECT '2'::zdecimal > 5;
SELECT 2 > '5'::zdecimal;
SELECT '5'::zdecimal > 2;
SELECT 5 > '2'::zdecimal;
SELECT '2'::zdecimal + 5;
SELECT 2 + '5'::zdecimal;
SELECT '5'::zdecimal + 2;
SELECT 5 + '2'::zdecimal;
SELECT '2'::zdecimal - 5;
SELECT 2 - '5'::zdecimal;
SELECT '5'::zdecimal - 2;
SELECT 5 - '2'::zdecimal;
SELECT '2'::zdecimal * 5;
SELECT 2 * '5'::zdecimal;
SELECT '5'::zdecimal * 2;
SELECT 5 * '2'::zdecimal;
SELECT '2'::zdecimal / 5;
SELECT 2 / '5'::zdecimal;
SELECT '5'::zdecimal / 2;
SELECT 5 / '2'::zdecimal;
SELECT '1'::zdecimal < '1'::zdecimal;
SELECT '5'::zdecimal < '2'::zdecimal;
SELECT '3'::zdecimal < '4'::zdecimal;
SELECT '1'::zdecimal <= '1'::zdecimal;
SELECT '5'::zdecimal <= '2'::zdecimal;
SELECT '3'::zdecimal <= '4'::zdecimal;
SELECT '1'::zdecimal = '1'::zdecimal;
SELECT '5'::zdecimal = '2'::zdecimal;
SELECT '3'::zdecimal = '4'::zdecimal;
SELECT '1'::zdecimal <> '1'::zdecimal;
SELECT '5'::zdecimal <> '2'::zdecimal;
SELECT '3'::zdecimal <> '4'::zdecimal;
SELECT '1'::zdecimal >= '1'::zdecimal;
SELECT '5'::zdecimal >= '2'::zdecimal;
SELECT '3'::zdecimal >= '4'::zdecimal;
SELECT '1'::zdecimal > '1'::zdecimal;
SELECT '5'::zdecimal > '2'::zdecimal;
SELECT '3'::zdecimal > '4'::zdecimal;

SELECT zdecimalcmp('1'::zdecimal, '1'::zdecimal);
SELECT zdecimalcmp('5'::zdecimal, '2'::zdecimal);
SELECT zdecimalcmp('3'::zdecimal, '4'::zdecimal);
SELECT pg_typeof('1'::zdecimal + '1'::zdecimal);
SELECT '1'::zdecimal + '1'::zdecimal;
SELECT '3'::zdecimal + '4'::zdecimal;
SELECT '5'::zdecimal + '2'::zdecimal;
SELECT '-3'::zdecimal + '4'::zdecimal;
SELECT '-5'::zdecimal + '2'::zdecimal;
SELECT '3'::zdecimal + '-4'::zdecimal;
SELECT '5'::zdecimal + '-2'::zdecimal;
SELECT '127'::zdecimal + '127'::zdecimal;
SELECT pg_typeof('1'::zdecimal - '1'::zdecimal);
SELECT '1'::zdecimal - '1'::zdecimal;
SELECT '3'::zdecimal - '4'::zdecimal;
SELECT '5'::zdecimal - '2'::zdecimal;
SELECT '-3'::zdecimal - '4'::zdecimal;
SELECT '-5'::zdecimal - '2'::zdecimal;
SELECT '3'::zdecimal - '-4'::zdecimal;
SELECT '5'::zdecimal - '-2'::zdecimal;
SELECT pg_typeof('1'::zdecimal * '1'::zdecimal);
SELECT '1'::zdecimal * '1'::zdecimal;
SELECT '3'::zdecimal * '4'::zdecimal;
SELECT '5'::zdecimal * '2'::zdecimal;
SELECT '-3'::zdecimal * '4'::zdecimal;
SELECT '-5'::zdecimal * '2'::zdecimal;
SELECT '3'::zdecimal * '-4'::zdecimal;
SELECT '5'::zdecimal * '-2'::zdecimal;
SELECT '127'::zdecimal * '127'::zdecimal;
SELECT pg_typeof('1'::zdecimal / '1'::zdecimal);
SELECT '1'::zdecimal / '1'::zdecimal;
SELECT '3'::zdecimal / '4'::zdecimal;
SELECT '5'::zdecimal / '2'::zdecimal;
SELECT '-3'::zdecimal / '4'::zdecimal;
SELECT '-5'::zdecimal / '2'::zdecimal;
SELECT '3'::zdecimal / '-4'::zdecimal;
SELECT '5'::zdecimal / '-2'::zdecimal;
SELECT '5'::zdecimal / '0'::zdecimal;

SELECT CAST('42.01'::zdecimal AS int8);
SELECT CAST('-42.01'::zdecimal AS int8);

SELECT CAST('42.01'::zdecimal AS double precision);
SELECT CAST('-42.01'::zdecimal AS double precision);

SELECT CAST('42.01'::zdecimal AS numeric);
SELECT CAST('-42.01'::zdecimal AS numeric);

SELECT zdecimal_hash(42.01);

SELECT zdecimal_hash(42.01::zdecimal);
